#!/bin/bash
if [ -n "$OSG_WN_CLIENT" ]; then
    . $OSG_WN_CLIENT/setup.sh
elif [ -n "$OSG_BASE_DIR" ]; then
    export X509_CERT_DIR=$OSG_BASE_DIR/etc/grid-security/certificates
    export X509_VOMS_DIR=$OSG_BASE_DIR/etc/grid-security/vomsdir
    export VOMS_USERCONF=$OSG_BASE_DIR/etc/vomses
fi
exec $CVMFS_DIST/usr/libexec/cvmfs/authz/cvmfs_x509_helper "$@"
