if [ -n "$CVMFS_VERSION_NUMERIC" ] && [ "$CVMFS_VERSION_NUMERIC" -ge 21401 ]; then
    CVMFS_EXTERNAL_METALINK="https://osdf-directors.osg-htc.org;https://osdf-director.osg-htc.org;https://osdf-director2.osg-htc.org"
fi
